[project]
name = "botanical-trees"
version = "0.1.0"
description = "Add a short description here"
authors = ["Corbin Charpentier <corbin.charpentier@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.10"

[pypi-dependencies]
bpy = "*"
